### ISSUE TITLE
Error related to PointWeights

### ISSUE THREAD

**Issue by auranic** [j-bac/elpigraph-python#16]
The following code which was functional in year 2021, does not work now:

url="https://raw.githubusercontent.com/j-bac/elpigraph-python/master/data/tree_data.csv"
df=pd.read_csv(url)
data = df.to_numpy()
PG = elpigraph.computeElasticPrincipalGraphWithGrammars(data,
                                           NumNodes=10,
                                           Mu=0.1, # elasticity for 'bending'
                                           Lambda=0.01, # elasticity for 'stretching'
                                           alpha = 0.01, # penalty for branching
                                           FinalEnergy = 'Penalized', # if 'Penalized' then penalty for branching is applied
                                           TrimmingRadius=0.3,#float('inf'), # Trimming radius, aka robustness radius
                                           GrammarOrder=['Grow', 'Shrink'], # Order of grammar applications
                                           GrowGrammars = np.array([['bisectedge','addnode2node'],['bisectedge','addnode2node']]),
                                           ShrinkGrammars = np.array([['shrinkedge','removenode']]),
                                           StoreGraphEvolution=True,
                                           verbose=True,
                                           GPU=False)[0]
                                           
gives error message :

Generating the initial configuration
Creating a chain in the 1st PC with 3 nodes
90% of the points have been used as initial conditions. Resetting.
Constructing tree 1 of 1 / Subset 1 of 1
Performing PCA
Using standard PCA
3 dimensions are being used
100.0 % of the original variance has been retained
Computing EPG with  10  nodes on  491  points and  3  dimensions

BARCODE	ENERGY	NNODES	NEDGES	NRIBS	NSTARS	NRAYS	NRAYS2	MSE	MSEP	FVE	FVEP	UE	UR	URN	URN2	URSD

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-7-66fd1c5d50c9>](https://localhost:8080/#) in <cell line: 1>()
----> 1 PG = elpigraph.computeElasticPrincipalGraphWithGrammars(data,
      2                                            NumNodes=10,
      3                                            Mu=0.1, # elasticity for 'bending'
      4                                            Lambda=0.01, # elasticity for 'stretching'
      5                                            alpha = 0.01, # penalty for branching

5 frames
[/usr/local/lib/python3.10/dist-packages/elpigraph/src/grammar_operations.py](https://localhost:8080/#) in AddNode2Node(X, NodePositions, ElasticMatrix, partition, AdjustVect, FixNodesAtPoints, Max_K, MaxNumberOfGraphCandidates, PointWeights)
    312     # add pointweights here if added
    313     if PointWeights is not None:
--> 314         assoc = np.bincount(
    315             partition[partition > -1].ravel(),
    316             weights=PointWeights.ravel(),

ValueError: The weights and list don't have the same length.

**Comment by j-bac** [comment]
Fixed it with version 0.3.2. Cheers!
