### ISSUE TITLE
Discrepancies in results from python and R implementation

### ISSUE THREAD

**Issue by kunamneni117** [j-bac/elpigraph-python#4]
While using python implementation of elpigraph,it is failed to output same results while taking [R](https://github.com/Albluca/ElPiGraph.R) implemented elpigraph outputs in reference(`Same Inputs and  parameters are Used`).I checked the default parameters in both libraries,expect `AvoidResampling`, everything is same and i tried changing the very hyper parameter(`AvoidResampling` to `False`) and checked but it outputs different results which are not same as R implementation result.

I have used  the [tree data](https://github.com/j-bac/elpigraph-python/blob/master/data/tree_data.csv) which is in the same repository  for doing sanity checks.Interestingly I found computeelasticprincipaltree only outputs different results when used the data provided.But when i tried with our own data all the three principal graphs outputs different results.
Attaching the observations for reference.

CALCULATIONS | COMPUTE ELASTIC PRINCIPAL TREE-   PYTHON IMPLEMENTATION | COMPUTE ELASTIC PRINCIPAL TREE- R   IMPLEMENTATION
-- | -- | --
BARCODE | 1\|3\|\|60 | 1\|4\|\|60
ENERGY | 0.0086 | 0.008498
NNODES | 60 | 60
NEDGES | 59 | 59
NRIBS | 49 | 47
NSTARS | 3 | 4
NRAYS | 0 | 0
NRAYS2 | 0 | 0
MSE | 0.0031 | 0.003063
MSEP | 0.0025 | 0.002532
FVE | 0.9942 | 0.9943
FVEP | 0.9953 | 0.9953
UE | 0.0054 | 0.005321
UR | 0.0001 | 0.0001137
URN | 0.0079 | 0.006821
URN2 | 0.475 | 0.4092
URSD | 0 | 0

I have observed issues with other principal graph calculations too.

**Comment by j-bac** [comment]
Thanks for reporting; I think you are using the original R version coming from Luca Albergante's repository. I forgot to mention in the README that I noticed some bugs in his implementation and corrected them in my fork 
[here](https://github.com/j-bac/ElPiGraph.R)

Thus outputs of the Python version should be compared with my corrected fork and not the original repository
