### ISSUE TITLE
Supporting float32 type

### ISSUE THREAD

**Issue by auranic** [j-bac/elpigraph-python#7]
When passing to elpigraph a numpy array containing float32 values, I got the following typing error message. It could be of course fixed by casting X=X.astype(np.float64), but I am not sure it is clearly documented that the data must be of float64 type. Or, am I wrong?

>print(type(X),type(X[0,0]))

<class 'numpy.ndarray'> <class 'numpy.float32'>

>egr = elpigraph.computeElasticPrincipalCircle(X,50)

The initial number of nodes must be at least 3. This will be fixed
Generating the initial configuration
Creating a circle in the plane induced by the 1st and 2nd PCs with 3 nodes
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-269-2dabecfe9781> in <module>
      1 import elpigraph
----> 2 egr = elpigraph.computeElasticPrincipalCircle(X,50)

~/anaconda3/lib/python3.7/site-packages/elpigraph/_topologies.py in computeElasticPrincipalCircle(X, NumNodes, NumEdges, InitNodes, Lambda, Mu, GrammarOptimization, MaxSteps, GrammarOrder, MaxNumberOfIterations, TrimmingRadius, eps, Do_PCA, InitNodePositions, AdjustVect, ElasticMatrix, InitEdges, CenterData, ComputeMSEP, verbose, ShowTimer, ReduceDimension, drawAccuracyComplexity, drawPCAView, drawEnergy, n_cores, MinParOp, nReps, Subsets, ProbPoint, Mode, FinalEnergy, alpha, beta, Configuration, ICOver, DensityRadius, AvoidSolitary, EmbPointProb, SampleIC, AvoidResampling, AdjustElasticMatrix, AdjustElasticMatrix_Initial, Lambda_Initial, Mu_Initial, DisplayWarnings)
    201                                              Lambda_Initial = Lambda_Initial, Mu_Initial = Mu_Initial,
    202                                              DisplayWarnings = DisplayWarnings,
--> 203                                              MaxSteps = MaxSteps
    204                                              ))
    205 

~/anaconda3/lib/python3.7/site-packages/elpigraph/_BaseElPiWrapper.py in computeElasticPrincipalGraphWithGrammars(X, GrowGrammars, ShrinkGrammars, NumNodes, NumEdges, InitNodes, Lambda, Mu, GrammarOptimization, MaxSteps, GrammarOrder, MaxNumberOfIterations, TrimmingRadius, eps, Do_PCA, InitNodePositions, AdjustVect, ElasticMatrix, InitEdges, CenterData, ComputeMSEP, verbose, ShowTimer, ReduceDimension, drawAccuracyComplexity, drawPCAView, drawEnergy, n_cores, MinParOp, nReps, Subsets, ProbPoint, Mode, FinalEnergy, alpha, beta, Configuration, DensityRadius, AvoidSolitary, EmbPointProb, SampleIC, AvoidResampling, AdjustElasticMatrix, AdjustElasticMatrix_Initial, Lambda_Initial, Mu_Initial, DisplayWarnings)
    186                                                                     DensityRadius = DensityRadius)
    187 
--> 188                         Dist = np.min(PartialDistance(InitialConf['NodePositions'], X), axis=0)
    189 
    190                         if(DensityRadius):

~/anaconda3/lib/python3.7/site-packages/elpigraph/src/distutils.py in PartialDistance(A, B)
    189 
    190 def PartialDistance(A,B):
--> 191     a=euclidean_distance_square_numba(A,B)
    192     a[np.isnan(a)]=0
    193     return a

~/.local/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    399                 e.patch_message(msg)
    400 
--> 401             error_rewrite(e, 'typing')
    402         except errors.UnsupportedError as e:
    403             # Something unsupported is present in the user code, add help info

~/.local/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345 
    346         argtypes = []

~/.local/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    666             value = tp()
    667         if value.__traceback__ is not tb:
--> 668             raise value.with_traceback(tb)
    669         raise value
    670 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function dot at 0x7f0f201299e0>) with argument(s) of type(s): (array(float64, 2d, C), array(float32, 2d, C))
 * parameterized
In definition 0:
    TypingError: np.dot() arguments must all have the same dtype
    raised from /home/zinovyev/.local/lib/python3.7/site-packages/numba/typing/npydecl.py:961
In definition 1:
    TypingError: np.dot() arguments must all have the same dtype
    raised from /home/zinovyev/.local/lib/python3.7/site-packages/numba/typing/npydecl.py:961
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function dot at 0x7f0f201299e0>)
[2] During: typing of call at /home/zinovyev/anaconda3/lib/python3.7/site-packages/elpigraph/src/distutils.py (179)

File "../../../../../home/zinovyev/anaconda3/lib/python3.7/site-packages/elpigraph/src/distutils.py", line 179:
def euclidean_distance_square_numba(x1, x2):
    distances =  np.sqrt(-2 * np.dot(x1, x2.T) + np.expand_dims(sum_squares_2d_array_along_axis1(x1), axis=1) + sum_squares_2d_array_along_axis1(x2))
    ^

**Comment by j-bac** [comment]
Yes this is a known issue - I will modify numba compiled functions to fix this.
